### ISSUE TITLE
能否上架Microsoft Edge浏览器插件市场

### ISSUE THREAD

**Issue by buildyuan** [elegantYU/just-open-it#1]
期待增加的功能描述：
上架Microsoft Edge(chromium)浏览器插件市场

实现此功能带来的增益：
可以实现edge插件的自动更新

缺少此功能的影响：
无法自动更新

实现的思路：
已兼容chromium，发布一次即可
目前采用的是edge安装chrome版

**Comment by elegantYU** [comment]
收到，明天就发布edge版本的
