### ISSUE TITLE
建议站点设置全部放配置

### ISSUE THREAD

**Issue by cute-angelia** [elegantYU/just-open-it#3]
更新商店还是很麻烦的，google 审核很慢

我看了你的代码，只要配置正则配置就可以了。

建议站点设置全部放配置

类似下图：

![image](https://user-images.githubusercontent.com/26561606/119595775-a4e29900-be10-11eb-97c0-672d35136b07.png)

**Comment by elegantYU** [comment]
好主意！我下午摸鱼的时候就改成可配置的！
