### ISSUE TITLE
知乎点击查看回复，闪退无效，关闭拓展才能正常查看

### ISSUE THREAD

**Issue by yixingzhiwang** [elegantYU/just-open-it#5]

**Comment by elegantYU** [comment]
脚本已更新

**Comment by yixingzhiwang** [comment]
似乎没看见微软拓展商店有更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "elegantYU/just-open-it"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月18日(星期一) 晚上8:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [elegantYU/just-open-it] 知乎点击查看回复，闪退无效，关闭拓展才能正常查看 (Issue #5)





 
脚本已更新

**Comment by elegantYU** [comment]
@yixingzhiwang 现在只需更新 static/config.json 就可以了😎

**Comment by yixingzhiwang** [comment]
现在又有别的问题。。。消息点开以后点击回复就自动关闭消息页面。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "elegantYU/just-open-it"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月19日(星期二) 上午10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [elegantYU/just-open-it] 知乎点击查看回复，闪退无效，关闭拓展才能正常查看 (Issue #5)





 
@yixingzhiwang 现在只需更新 static/config.json 就可以了😎

**Comment by elegantYU** [comment]
@yixingzhiwang 😂后悔支持知乎去弹窗了...我晚上把判断再梳理一下
