### ISSUE TITLE
希望支持开源中国的

### ISSUE THREAD

**Issue by zhshuixian** [elegantYU/just-open-it#6]
![image](https://user-images.githubusercontent.com/46039358/143243931-1e3d1ac9-7ae3-46a8-9937-bd80c56a3b92.png)

**Comment by elegantYU** [comment]
这周我抽空搞一下

**Comment by zhshuixian** [comment]
是不是和简书一样，配置一下就 ok了。 如果是的话下面的配置就 ok了

```
		"name": "开源中国",
		"type": "href",
		"regExp": "L15odHRwKHN8KTpcL1wvd3d3XC5vc2NoaW5hXC5uZXRcL2FjdGlvblwvR29Ub0xpbmtcP3VybD0oLiopLw==",
		"jumpAction": {
			"type": "decode",
			"index": 2
		}
```

**Comment by elegantYU** [comment]
wow~厉害啊，公司活太多了一直没时间搞这个...

**Comment by elegantYU** [comment]
已经提交了，chrome://extensions 后台找到 just-open-it 背景页，清空下 localstorage 就会重新拉取配置（或者等明天
