### ISSUE TITLE
码云-Gitee 的支持

### ISSUE THREAD

**Issue by zhshuixian** [elegantYU/just-open-it#7]
![image](https://user-images.githubusercontent.com/46039358/144780505-218a51b4-ce26-46f6-a19c-a323f27cdbd8.png)

已经测好了，可以直接使用下面的配置：

正则表达式：/^http(s|):\/\/gitee\.com\/link\?target=(.*)/

```
		"name": "码云-Gitee",
		"type": "href",
		"regExp": "L15odHRwKHN8KTpcL1wvZ2l0ZWVcLmNvbVwvbGlua1w/dGFyZ2V0PSguKikv",
		"jumpAction": {
			"type": "decode",
			"index": 2
		}
```

**Comment by elegantYU** [comment]
已更新~
